import turtle
turtle.seth(0)
turtle.pencolor("red")
turtle.fd(200)
turtle.seth(120)
turtle.fd(200)
turtle.seth(-120)
turtle.fd(200)
turtle.up()
turtle.seth(0)
turtle.fd(100)
turtle.down()
turtle.color("black","yellow")
turtle.begin_fill()
for i in range(3):
    turtle.seth(60+120*i)
    turtle.fd(100)
turtle.end_fill()
turtle.seth(60)
turtle.fd(50)
turtle.color("red","white")
turtle.begin_fill()
for e in range(3):
    turtle.seth(120+120*e)
    turtle.fd(50)
turtle.end_fill()
